"""create posts comments boards crawl_state

Revision ID: 4856307c62e5
Revises:
Create Date: 2026-10-07 11:48:50.221724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4856307c62e5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("board", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("interval_sec", sa.Integer(), nullable=False),
        sa.Column("recrawl_min_push", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("interval_sec >= 30", name=op.f("ck_boards_interval_sec_min")),
        sa.CheckConstraint("recrawl_min_push >= 0", name=op.f("ck_boards_recrawl_min_push_nonneg")),
        sa.PrimaryKeyConstraint("board", name=op.f("pk_boards")),
        comment="writer: api; debezium: no",
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Text(), nullable=False),
        sa.Column("board", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("push_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("boo_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_posts")),
        comment="writer: ingest; debezium: yes",
    )
    op.create_index("ix_posts_created_at", "posts", ["created_at"], unique=False)
    # NOTE: comments.type 的 CHECK 由 sa.Enum(create_constraint=True) 自動建立，不重複宣告
    op.create_table(
        "comments",
        sa.Column("post_id", sa.Text(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "push",
                "boo",
                "arrow",
                name="comment_type",
                native_enum=False,
                create_constraint=True,
                length=8,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("commented_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.post_id"], name=op.f("fk_comments_post_id_posts")
        ),
        sa.PrimaryKeyConstraint("post_id", "floor", name=op.f("pk_comments")),
        comment="writer: ingest; debezium: yes",
    )
    op.create_table(
        "crawl_state",
        sa.Column("post_id", sa.Text(), nullable=False),
        sa.Column("next_crawl_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_dispatched", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.post_id"], name=op.f("fk_crawl_state_post_id_posts")
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_crawl_state")),
        comment="writer: scheduler; debezium: no",
    )
    op.create_index("ix_crawl_state_next_crawl_at", "crawl_state", ["next_crawl_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_crawl_state_next_crawl_at", table_name="crawl_state")
    op.drop_table("crawl_state")
    op.drop_table("comments")
    op.drop_index("ix_posts_created_at", table_name="posts")
    op.drop_table("posts")
    op.drop_table("boards")
    # ### end Alembic commands ###
