"""topics.yaml 管理的 topic 名稱；需與 infra/kafka/topics.yaml 一致（由單元測試檢查）。"""

CRAWL_TASKS = "crawl.tasks"
RAW_POSTS = "raw.posts"
RAW_HTML = "raw.html"
CDC_POSTS = "cdc.public.posts"
CDC_COMMENTS = "cdc.public.comments"
LABELS = "labels"
PREDICTIONS = "predictions"
ALERTS = "alerts"
DLQ = "dlq"
CDC_HEARTBEAT = "__debezium-heartbeat.cdc"
